spring:
  application:
    name: fornecedor
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: admin
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
